services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3333
      API_URL: http://backend:3333
      NODE_ENV: development
    volumes:
      # Mount source code for hot reload
      - ./frontend:/app
      # Preserve node_modules in container
      - /app/node_modules
      # Preserve .next directory for faster rebuilds
      - /app/.next
    ports:
      - "3000:3000"
    depends_on:
      - backend
    # Remove restart policy for development
    restart: "no" 